spring:
  application:
    name: vehicle
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true

server:
  servlet:
    context-path: /test
